import {StyleSheet, Platform} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
import colors from '../../styles/colors';
import Fonts from '../../styles/fonts';

export default StyleSheet.create({
  indicator: {
    color: colors.primary,
  },
  indicatorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  title: {
    fontWeight: 'bold',
    color: colors.fullBlack,
    fontSize: RFValue(12),
    fontFamily: Fonts.fontFamily.medium,
  },
  comment: {
    fontSize: RFValue(12),
    color: colors.comment,
    fontFamily: Fonts.fontFamily.regular,
  },
  avatar: {
    height: 50,
    width: 50,
    borderRadius: 25,
    marginHorizontal: 20,
  },
  top: {
    width: '100%',
    flexDirection: 'row',
    padding: 10,
    alignItems: 'center',
    elevation: 4,
    backgroundColor: '#ffffff',
  },
  wallletContainer: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: RFValue(70),
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    marginTop: 20,
    marginBottom: 10,
    alignSelf: 'center',
    borderRadius: 10,
    padding: RFValue(8),
    alignItems: 'center',
  },
  submitButton: {
    width: 150,
    right: RFValue(10),
    backgroundColor: colors.primary,
    height: RFValue(40),
    borderRadius: RFValue(10),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    fontWeight: '600',
  },
  buttonText: {
    fontWeight: 'bold',
    color: colors.white,
    fontSize: RFValue(13),
    fontFamily: Fonts.fontFamily.medium,
  },
  pdlock: {
    height: 20,
    width: 20,
    backgroundColor: 'gray',
    borderRadius: 10,
  },
  BvnContainer: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: RFValue(85),
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    marginTop: 10,
    marginBottom: 10,
    alignSelf: 'center',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
  },
  title2: {
    fontWeight: 'bold',
    color: colors.fullBlack,
    fontSize: RFValue(14),
    fontFamily: Fonts.fontFamily.medium,
  },
  moneyAvatar: {
    borderRadius: 33,
    borderStyle: 'solid',
    borderWidth: 3,
    borderColor: colors.primaryDark,
    marginHorizontal: 10,
  },
  row: {
    flexDirection: 'row',
  },
  inputText: {
    backgroundColor: '#F0F5F7',
    borderWidth: 1,
    height: RFValue(50),
    padding: RFValue(10),
    marginTop: RFValue(23),
    borderTopLeftRadius: RFValue(5),
    borderBottomLeftRadius: RFValue(5),
    borderColor: colors.white,
  },
  text: {
    backgroundColor: '#F0F5F7',
    borderWidth: 1,
    height: RFValue(50),
    padding: RFValue(10),
    marginTop: RFValue(23),
    lineHeight: RFValue(30),
    borderTopRightRadius: RFValue(5),
    borderBottomRightRadius: RFValue(5),
    borderColor: colors.white,
    fontSize: RFValue(12),
    color: '#652283',
    fontWeight: 'bold',
  },
  bottomContainer: {
    justifyContent: 'flex-end',
    marginTop: 170,
    alignItems: 'center',
  },
  request: {
    width: '35%',
    right: RFValue(10),
    backgroundColor: colors.fullBlack,
    height: RFValue(40),
    paddingVertical: RFValue(10),
    paddingLeft: RFValue(25),
    borderRadius: RFValue(10),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  miniIcon: {
    color: colors.white,
    height: 50,
    width: 50,
    marginLeft: RFValue(10),
    textAlignVertical: 'center',
    marginTop: Platform.OS === 'ios' ? RFValue(30) : 0,
  },
});
